name: Daily News Update

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: python3 scraper.py
      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: update
